version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: wx-book-converter-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis: 
    image: redis:6
    container_name: wx-book-converter-redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - redis:/data
volumes:
  postgres:
    name: nest-db
  redis:
    name: nest-redis
